import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader','--ignore-gpu-blocklist'] });
const p = await b.newPage({ viewport: { width: 1280, height: 760 } });
const errs = [];
p.on('console', m => { if (m.type() === 'error' || m.type()==='warning') errs.push(m.type()+': '+m.text()); });
p.on('pageerror', e => errs.push('PAGEERR ' + e.message));
await p.goto('file://' + process.cwd() + '/dist/ballistic.html');
await p.waitForTimeout(2500);
await p.screenshot({ path: 'shots/menu.png' });
await p.click('#play');
await p.waitForTimeout(3800);
await p.mouse.move(900, 300);
await p.keyboard.down('d'); await p.mouse.down();
await p.waitForTimeout(1500);
await p.keyboard.up('d'); await p.keyboard.down('w');
await p.waitForTimeout(1200); await p.mouse.up(); await p.keyboard.up('w');
await p.mouse.click(700, 200, { button: 'right' });
await p.waitForTimeout(1500);
await p.screenshot({ path: 'shots/play1.png' });
await p.waitForTimeout(12000);
await p.screenshot({ path: 'shots/play2.png' });
const st = await p.evaluate(() => { const g = window.__game; return { state: g.state, t: g.matchT.toFixed(1), kills: g.babos.map(b => b.name + ':' + b.kills + '/' + b.deaths + (b.alive ? '' : '(dead)') + ' ' + b.x.toFixed(1)+','+b.z.toFixed(1)), q: g.r.quality }; });
console.log(JSON.stringify(st, null, 1));
console.log(errs.slice(0, 15).join('\n'));
await b.close();
