import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome', args: ['--no-proxy-server','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const ctx = await b.newContext({ viewport: { width: 1280, height: 800 } });
await ctx.addInitScript({ path: 'mockroom.js' });
await ctx.route(/fonts\.(googleapis|gstatic)\.com/, r => r.abort());
const errs = [];
const p = await ctx.newPage(); p.on('pageerror', e => errs.push('PAGEERR ' + e.message));
await p.goto('http://127.0.0.1:8765/ballistic.html', { waitUntil: 'domcontentloaded' }); await p.waitForTimeout(2000);
await p.keyboard.press('f');
await p.screenshot({ path: 'shots/menu2.png' });
await p.click('#play-online'); await p.waitForTimeout(1200);
await p.screenshot({ path: 'shots/lobby.png' });
await p.click('#lobby-back');
await p.evaluate(() => { const g = window.__game; g.saved.ability = 'spikes'; g.pendingAbility = 'spikes'; });
await p.click('#play');
await p.evaluate(() => { const g = window.__game; g.frame = () => {}; for (let i = 0; i < 60 * 12; i++) g.tick(1/60, false);
  const P = g.player; if (!P.alive) g.spawn(P); const t = g.babos.find(b => !b.isPlayer && b.alive); P.x = t.x + 1.2; P.z = t.z; P.abCool = 0; g.input.abilityQueued = true; g.tick(1/60, false); g.tick(1/60, false);
  const t2 = g.babos.find(b => !b.isPlayer && b.alive && b !== t); t2.ability = 'bubble'; t2.abCool = 0; g.useAbility(t2);
  for (let i = 0; i < 6; i++) g.tick(1/60, false); g.tick(1/60, true); });
await p.screenshot({ path: 'shots/ability.png' });
console.log(errs.join('\n'));
await b.close();
